# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.content_gem_api import ContentGemApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentGemApi(unittest.TestCase):
    """ContentGemApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.content_gem_api.ContentGemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_gem_gem_create(self):
        """Test case for content_gem_gem_create

        Create a gem content  # noqa: E501
        """
        pass

    def test_content_gem_gem_list(self):
        """Test case for content_gem_gem_list

        List gem contents  # noqa: E501
        """
        pass

    def test_content_gem_gem_read(self):
        """Test case for content_gem_gem_read

        Inspect a gem content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
