# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.contentguards_composite_api import ContentguardsCompositeApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentguardsCompositeApi(unittest.TestCase):
    """ContentguardsCompositeApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.contentguards_composite_api.ContentguardsCompositeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contentguards_core_composite_add_role(self):
        """Test case for contentguards_core_composite_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_create(self):
        """Test case for contentguards_core_composite_create

        Create a composite content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_delete(self):
        """Test case for contentguards_core_composite_delete

        Delete a composite content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_list(self):
        """Test case for contentguards_core_composite_list

        List composite content guards  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_list_roles(self):
        """Test case for contentguards_core_composite_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_my_permissions(self):
        """Test case for contentguards_core_composite_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_partial_update(self):
        """Test case for contentguards_core_composite_partial_update

        Update a composite content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_read(self):
        """Test case for contentguards_core_composite_read

        Inspect a composite content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_remove_role(self):
        """Test case for contentguards_core_composite_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_contentguards_core_composite_update(self):
        """Test case for contentguards_core_composite_update

        Update a composite content guard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
