# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.contentguards_rbac_api import ContentguardsRbacApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentguardsRbacApi(unittest.TestCase):
    """ContentguardsRbacApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.contentguards_rbac_api.ContentguardsRbacApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contentguards_core_rbac_add_role(self):
        """Test case for contentguards_core_rbac_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_create(self):
        """Test case for contentguards_core_rbac_create

        Create a rbac content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_delete(self):
        """Test case for contentguards_core_rbac_delete

        Delete a rbac content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_list(self):
        """Test case for contentguards_core_rbac_list

        List rbac content guards  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_list_roles(self):
        """Test case for contentguards_core_rbac_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_my_permissions(self):
        """Test case for contentguards_core_rbac_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_partial_update(self):
        """Test case for contentguards_core_rbac_partial_update

        Update a rbac content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_read(self):
        """Test case for contentguards_core_rbac_read

        Inspect a rbac content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_remove_role(self):
        """Test case for contentguards_core_rbac_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_contentguards_core_rbac_update(self):
        """Test case for contentguards_core_rbac_update

        Update a rbac content guard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
