# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.exporters_filesystem_api import ExportersFilesystemApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestExportersFilesystemApi(unittest.TestCase):
    """ExportersFilesystemApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.exporters_filesystem_api.ExportersFilesystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exporters_core_filesystem_create(self):
        """Test case for exporters_core_filesystem_create

        Create a filesystem exporter  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_delete(self):
        """Test case for exporters_core_filesystem_delete

        Delete a filesystem exporter  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_list(self):
        """Test case for exporters_core_filesystem_list

        List filesystem exporters  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_partial_update(self):
        """Test case for exporters_core_filesystem_partial_update

        Update a filesystem exporter  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_read(self):
        """Test case for exporters_core_filesystem_read

        Inspect a filesystem exporter  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_update(self):
        """Test case for exporters_core_filesystem_update

        Update a filesystem exporter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
