# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.repositories_rpm_versions_api import RepositoriesRpmVersionsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRepositoriesRpmVersionsApi(unittest.TestCase):
    """RepositoriesRpmVersionsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.repositories_rpm_versions_api.RepositoriesRpmVersionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repositories_rpm_rpm_versions_delete(self):
        """Test case for repositories_rpm_rpm_versions_delete

        Delete a repository version  # noqa: E501
        """
        pass

    def test_repositories_rpm_rpm_versions_list(self):
        """Test case for repositories_rpm_rpm_versions_list

        List repository versions  # noqa: E501
        """
        pass

    def test_repositories_rpm_rpm_versions_read(self):
        """Test case for repositories_rpm_rpm_versions_read

        Inspect a repository version  # noqa: E501
        """
        pass

    def test_repositories_rpm_rpm_versions_repair(self):
        """Test case for repositories_rpm_rpm_versions_repair

        """
        pass


if __name__ == '__main__':
    unittest.main()
