# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.exporters_filesystem_exports_api import ExportersFilesystemExportsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestExportersFilesystemExportsApi(unittest.TestCase):
    """ExportersFilesystemExportsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.exporters_filesystem_exports_api.ExportersFilesystemExportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exporters_core_filesystem_exports_create(self):
        """Test case for exporters_core_filesystem_exports_create

        Create a filesystem export  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_exports_delete(self):
        """Test case for exporters_core_filesystem_exports_delete

        Delete a filesystem export  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_exports_list(self):
        """Test case for exporters_core_filesystem_exports_list

        List filesystem exports  # noqa: E501
        """
        pass

    def test_exporters_core_filesystem_exports_read(self):
        """Test case for exporters_core_filesystem_exports_read

        Inspect a filesystem export  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
