# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.remotes_uln_api import RemotesUlnApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRemotesUlnApi(unittest.TestCase):
    """RemotesUlnApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.remotes_uln_api.RemotesUlnApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_remotes_rpm_uln_add_role(self):
        """Test case for remotes_rpm_uln_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_create(self):
        """Test case for remotes_rpm_uln_create

        Create an uln remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_delete(self):
        """Test case for remotes_rpm_uln_delete

        Delete an uln remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_list(self):
        """Test case for remotes_rpm_uln_list

        List uln remotes  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_list_roles(self):
        """Test case for remotes_rpm_uln_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_my_permissions(self):
        """Test case for remotes_rpm_uln_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_partial_update(self):
        """Test case for remotes_rpm_uln_partial_update

        Update an uln remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_read(self):
        """Test case for remotes_rpm_uln_read

        Inspect an uln remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_remove_role(self):
        """Test case for remotes_rpm_uln_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_set_label(self):
        """Test case for remotes_rpm_uln_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_unset_label(self):
        """Test case for remotes_rpm_uln_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_remotes_rpm_uln_update(self):
        """Test case for remotes_rpm_uln_update

        Update an uln remote  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
