# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.uploads_api import UploadsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.uploads_api.UploadsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_uploads_add_role(self):
        """Test case for uploads_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_uploads_commit(self):
        """Test case for uploads_commit

        Finish an Upload  # noqa: E501
        """
        pass

    def test_uploads_create(self):
        """Test case for uploads_create

        Create an upload  # noqa: E501
        """
        pass

    def test_uploads_delete(self):
        """Test case for uploads_delete

        Delete an upload  # noqa: E501
        """
        pass

    def test_uploads_list(self):
        """Test case for uploads_list

        List uploads  # noqa: E501
        """
        pass

    def test_uploads_list_roles(self):
        """Test case for uploads_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_uploads_my_permissions(self):
        """Test case for uploads_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_uploads_read(self):
        """Test case for uploads_read

        Inspect an upload  # noqa: E501
        """
        pass

    def test_uploads_remove_role(self):
        """Test case for uploads_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_uploads_update(self):
        """Test case for uploads_update

        Upload a file chunk  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
