# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.upstream_pulps_api import UpstreamPulpsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestUpstreamPulpsApi(unittest.TestCase):
    """UpstreamPulpsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.upstream_pulps_api.UpstreamPulpsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upstream_pulps_add_role(self):
        """Test case for upstream_pulps_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_upstream_pulps_create(self):
        """Test case for upstream_pulps_create

        Create an upstream pulp  # noqa: E501
        """
        pass

    def test_upstream_pulps_delete(self):
        """Test case for upstream_pulps_delete

        Delete an upstream pulp  # noqa: E501
        """
        pass

    def test_upstream_pulps_list(self):
        """Test case for upstream_pulps_list

        List upstream pulps  # noqa: E501
        """
        pass

    def test_upstream_pulps_list_roles(self):
        """Test case for upstream_pulps_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_upstream_pulps_my_permissions(self):
        """Test case for upstream_pulps_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_upstream_pulps_partial_update(self):
        """Test case for upstream_pulps_partial_update

        Update an upstream pulp  # noqa: E501
        """
        pass

    def test_upstream_pulps_read(self):
        """Test case for upstream_pulps_read

        Inspect an upstream pulp  # noqa: E501
        """
        pass

    def test_upstream_pulps_remove_role(self):
        """Test case for upstream_pulps_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_upstream_pulps_replicate(self):
        """Test case for upstream_pulps_replicate

        Replicate  # noqa: E501
        """
        pass

    def test_upstream_pulps_update(self):
        """Test case for upstream_pulps_update

        Update an upstream pulp  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
