# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.repositories_ostree_api import RepositoriesOstreeApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRepositoriesOstreeApi(unittest.TestCase):
    """RepositoriesOstreeApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.repositories_ostree_api.RepositoriesOstreeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repositories_ostree_ostree_add_role(self):
        """Test case for repositories_ostree_ostree_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_create(self):
        """Test case for repositories_ostree_ostree_create

        Create an ostree repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_delete(self):
        """Test case for repositories_ostree_ostree_delete

        Delete an ostree repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_import_all(self):
        """Test case for repositories_ostree_ostree_import_all

        Import refs and commits to a repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_import_commits(self):
        """Test case for repositories_ostree_ostree_import_commits

        Append child commits to a repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_list(self):
        """Test case for repositories_ostree_ostree_list

        List ostree repositorys  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_list_roles(self):
        """Test case for repositories_ostree_ostree_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_modify(self):
        """Test case for repositories_ostree_ostree_modify

        Modify repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_my_permissions(self):
        """Test case for repositories_ostree_ostree_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_partial_update(self):
        """Test case for repositories_ostree_ostree_partial_update

        Update an ostree repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_read(self):
        """Test case for repositories_ostree_ostree_read

        Inspect an ostree repository  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_remove_role(self):
        """Test case for repositories_ostree_ostree_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_set_label(self):
        """Test case for repositories_ostree_ostree_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_sync(self):
        """Test case for repositories_ostree_ostree_sync

        Sync from remote  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_unset_label(self):
        """Test case for repositories_ostree_ostree_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_repositories_ostree_ostree_update(self):
        """Test case for repositories_ostree_ostree_update

        Update an ostree repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
