# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.domains_api import DomainsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.domains_api.DomainsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_domains_create(self):
        """Test case for domains_create

        Create a domain  # noqa: E501
        """
        pass

    def test_domains_delete(self):
        """Test case for domains_delete

        Delete a domain  # noqa: E501
        """
        pass

    def test_domains_list(self):
        """Test case for domains_list

        List domains  # noqa: E501
        """
        pass

    def test_domains_partial_update(self):
        """Test case for domains_partial_update

        Update a domain  # noqa: E501
        """
        pass

    def test_domains_read(self):
        """Test case for domains_read

        Inspect a domain  # noqa: E501
        """
        pass

    def test_domains_update(self):
        """Test case for domains_update

        Update a domain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
