# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.tasks_api import TasksApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_add_role(self):
        """Test case for tasks_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_tasks_cancel(self):
        """Test case for tasks_cancel

        Cancel a task  # noqa: E501
        """
        pass

    def test_tasks_delete(self):
        """Test case for tasks_delete

        Delete a task  # noqa: E501
        """
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        List tasks  # noqa: E501
        """
        pass

    def test_tasks_list_roles(self):
        """Test case for tasks_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_tasks_my_permissions(self):
        """Test case for tasks_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_tasks_purge(self):
        """Test case for tasks_purge

        Purge Completed Tasks  # noqa: E501
        """
        pass

    def test_tasks_read(self):
        """Test case for tasks_read

        Inspect a task  # noqa: E501
        """
        pass

    def test_tasks_remove_role(self):
        """Test case for tasks_remove_role

        Remove a role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
