# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.content_files_api import ContentFilesApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentFilesApi(unittest.TestCase):
    """ContentFilesApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.content_files_api.ContentFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_file_files_create(self):
        """Test case for content_file_files_create

        Create a file content  # noqa: E501
        """
        pass

    def test_content_file_files_list(self):
        """Test case for content_file_files_list

        List file contents  # noqa: E501
        """
        pass

    def test_content_file_files_read(self):
        """Test case for content_file_files_read

        Inspect a file content  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
