# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.distributions_pypi_api import DistributionsPypiApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestDistributionsPypiApi(unittest.TestCase):
    """DistributionsPypiApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.distributions_pypi_api.DistributionsPypiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_distributions_python_pypi_add_role(self):
        """Test case for distributions_python_pypi_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_create(self):
        """Test case for distributions_python_pypi_create

        Create a python distribution  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_delete(self):
        """Test case for distributions_python_pypi_delete

        Delete a python distribution  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_list(self):
        """Test case for distributions_python_pypi_list

        List python distributions  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_list_roles(self):
        """Test case for distributions_python_pypi_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_my_permissions(self):
        """Test case for distributions_python_pypi_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_partial_update(self):
        """Test case for distributions_python_pypi_partial_update

        Update a python distribution  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_read(self):
        """Test case for distributions_python_pypi_read

        Inspect a python distribution  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_remove_role(self):
        """Test case for distributions_python_pypi_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_set_label(self):
        """Test case for distributions_python_pypi_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_unset_label(self):
        """Test case for distributions_python_pypi_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_distributions_python_pypi_update(self):
        """Test case for distributions_python_pypi_update

        Update a python distribution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
