# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.repositories_python_api import RepositoriesPythonApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRepositoriesPythonApi(unittest.TestCase):
    """RepositoriesPythonApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.repositories_python_api.RepositoriesPythonApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repositories_python_python_add_role(self):
        """Test case for repositories_python_python_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_repositories_python_python_create(self):
        """Test case for repositories_python_python_create

        Create a python repository  # noqa: E501
        """
        pass

    def test_repositories_python_python_delete(self):
        """Test case for repositories_python_python_delete

        Delete a python repository  # noqa: E501
        """
        pass

    def test_repositories_python_python_list(self):
        """Test case for repositories_python_python_list

        List python repositorys  # noqa: E501
        """
        pass

    def test_repositories_python_python_list_roles(self):
        """Test case for repositories_python_python_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_repositories_python_python_modify(self):
        """Test case for repositories_python_python_modify

        Modify Repository Content  # noqa: E501
        """
        pass

    def test_repositories_python_python_my_permissions(self):
        """Test case for repositories_python_python_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_repositories_python_python_partial_update(self):
        """Test case for repositories_python_python_partial_update

        Update a python repository  # noqa: E501
        """
        pass

    def test_repositories_python_python_read(self):
        """Test case for repositories_python_python_read

        Inspect a python repository  # noqa: E501
        """
        pass

    def test_repositories_python_python_remove_role(self):
        """Test case for repositories_python_python_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_repositories_python_python_set_label(self):
        """Test case for repositories_python_python_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_repositories_python_python_sync(self):
        """Test case for repositories_python_python_sync

        Sync from remote  # noqa: E501
        """
        pass

    def test_repositories_python_python_unset_label(self):
        """Test case for repositories_python_python_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_repositories_python_python_update(self):
        """Test case for repositories_python_python_update

        Update a python repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
