# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.exporters_pulp_api import ExportersPulpApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestExportersPulpApi(unittest.TestCase):
    """ExportersPulpApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.exporters_pulp_api.ExportersPulpApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_exporters_core_pulp_create(self):
        """Test case for exporters_core_pulp_create

        Create a pulp exporter  # noqa: E501
        """
        pass

    def test_exporters_core_pulp_delete(self):
        """Test case for exporters_core_pulp_delete

        Delete a pulp exporter  # noqa: E501
        """
        pass

    def test_exporters_core_pulp_list(self):
        """Test case for exporters_core_pulp_list

        List pulp exporters  # noqa: E501
        """
        pass

    def test_exporters_core_pulp_partial_update(self):
        """Test case for exporters_core_pulp_partial_update

        Update a pulp exporter  # noqa: E501
        """
        pass

    def test_exporters_core_pulp_read(self):
        """Test case for exporters_core_pulp_read

        Inspect a pulp exporter  # noqa: E501
        """
        pass

    def test_exporters_core_pulp_update(self):
        """Test case for exporters_core_pulp_update

        Update a pulp exporter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
