# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.content_modulemd_defaults_api import ContentModulemdDefaultsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentModulemdDefaultsApi(unittest.TestCase):
    """ContentModulemdDefaultsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.content_modulemd_defaults_api.ContentModulemdDefaultsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_rpm_modulemd_defaults_create(self):
        """Test case for content_rpm_modulemd_defaults_create

        Create a modulemd defaults  # noqa: E501
        """
        pass

    def test_content_rpm_modulemd_defaults_list(self):
        """Test case for content_rpm_modulemd_defaults_list

        List modulemd defaultss  # noqa: E501
        """
        pass

    def test_content_rpm_modulemd_defaults_read(self):
        """Test case for content_rpm_modulemd_defaults_read

        Inspect a modulemd defaults  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
