# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.remotes_rpm_api import RemotesRpmApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRemotesRpmApi(unittest.TestCase):
    """RemotesRpmApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.remotes_rpm_api.RemotesRpmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_remotes_rpm_rpm_add_role(self):
        """Test case for remotes_rpm_rpm_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_create(self):
        """Test case for remotes_rpm_rpm_create

        Create a rpm remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_delete(self):
        """Test case for remotes_rpm_rpm_delete

        Delete a rpm remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_list(self):
        """Test case for remotes_rpm_rpm_list

        List rpm remotes  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_list_roles(self):
        """Test case for remotes_rpm_rpm_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_my_permissions(self):
        """Test case for remotes_rpm_rpm_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_partial_update(self):
        """Test case for remotes_rpm_rpm_partial_update

        Update a rpm remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_read(self):
        """Test case for remotes_rpm_rpm_read

        Inspect a rpm remote  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_remove_role(self):
        """Test case for remotes_rpm_rpm_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_set_label(self):
        """Test case for remotes_rpm_rpm_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_unset_label(self):
        """Test case for remotes_rpm_rpm_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_remotes_rpm_rpm_update(self):
        """Test case for remotes_rpm_rpm_update

        Update a rpm remote  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
