# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.contentguards_content_redirect_api import ContentguardsContentRedirectApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentguardsContentRedirectApi(unittest.TestCase):
    """ContentguardsContentRedirectApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.contentguards_content_redirect_api.ContentguardsContentRedirectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contentguards_core_content_redirect_add_role(self):
        """Test case for contentguards_core_content_redirect_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_create(self):
        """Test case for contentguards_core_content_redirect_create

        Create a content redirect content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_delete(self):
        """Test case for contentguards_core_content_redirect_delete

        Delete a content redirect content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_list(self):
        """Test case for contentguards_core_content_redirect_list

        List content redirect content guards  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_list_roles(self):
        """Test case for contentguards_core_content_redirect_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_my_permissions(self):
        """Test case for contentguards_core_content_redirect_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_partial_update(self):
        """Test case for contentguards_core_content_redirect_partial_update

        Update a content redirect content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_read(self):
        """Test case for contentguards_core_content_redirect_read

        Inspect a content redirect content guard  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_remove_role(self):
        """Test case for contentguards_core_content_redirect_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_contentguards_core_content_redirect_update(self):
        """Test case for contentguards_core_content_redirect_update

        Update a content redirect content guard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
