# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.importers_pulp_api import ImportersPulpApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestImportersPulpApi(unittest.TestCase):
    """ImportersPulpApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.importers_pulp_api.ImportersPulpApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_importers_core_pulp_create(self):
        """Test case for importers_core_pulp_create

        Create a pulp importer  # noqa: E501
        """
        pass

    def test_importers_core_pulp_delete(self):
        """Test case for importers_core_pulp_delete

        Delete a pulp importer  # noqa: E501
        """
        pass

    def test_importers_core_pulp_list(self):
        """Test case for importers_core_pulp_list

        List pulp importers  # noqa: E501
        """
        pass

    def test_importers_core_pulp_partial_update(self):
        """Test case for importers_core_pulp_partial_update

        Update a pulp importer  # noqa: E501
        """
        pass

    def test_importers_core_pulp_read(self):
        """Test case for importers_core_pulp_read

        Inspect a pulp importer  # noqa: E501
        """
        pass

    def test_importers_core_pulp_update(self):
        """Test case for importers_core_pulp_update

        Update a pulp importer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
