# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.groups_api import GroupsApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_add_role(self):
        """Test case for groups_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_groups_create(self):
        """Test case for groups_create

        Create a group  # noqa: E501
        """
        pass

    def test_groups_delete(self):
        """Test case for groups_delete

        Delete a group  # noqa: E501
        """
        pass

    def test_groups_list(self):
        """Test case for groups_list

        List groups  # noqa: E501
        """
        pass

    def test_groups_list_roles(self):
        """Test case for groups_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_groups_my_permissions(self):
        """Test case for groups_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_groups_partial_update(self):
        """Test case for groups_partial_update

        Update a group  # noqa: E501
        """
        pass

    def test_groups_read(self):
        """Test case for groups_read

        Inspect a group  # noqa: E501
        """
        pass

    def test_groups_remove_role(self):
        """Test case for groups_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_groups_update(self):
        """Test case for groups_update

        Update a group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
