# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.contentguards_x509_api import ContentguardsX509Api  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestContentguardsX509Api(unittest.TestCase):
    """ContentguardsX509Api unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.contentguards_x509_api.ContentguardsX509Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_contentguards_certguard_x509_create(self):
        """Test case for contentguards_certguard_x509_create

        Create a x509 cert guard  # noqa: E501
        """
        pass

    def test_contentguards_certguard_x509_delete(self):
        """Test case for contentguards_certguard_x509_delete

        Delete a x509 cert guard  # noqa: E501
        """
        pass

    def test_contentguards_certguard_x509_list(self):
        """Test case for contentguards_certguard_x509_list

        List x509 cert guards  # noqa: E501
        """
        pass

    def test_contentguards_certguard_x509_partial_update(self):
        """Test case for contentguards_certguard_x509_partial_update

        Update a x509 cert guard  # noqa: E501
        """
        pass

    def test_contentguards_certguard_x509_read(self):
        """Test case for contentguards_certguard_x509_read

        Inspect a x509 cert guard  # noqa: E501
        """
        pass

    def test_contentguards_certguard_x509_update(self):
        """Test case for contentguards_certguard_x509_update

        Update a x509 cert guard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
