# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.access_policies_api import AccessPoliciesApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestAccessPoliciesApi(unittest.TestCase):
    """AccessPoliciesApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.access_policies_api.AccessPoliciesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_access_policies_list(self):
        """Test case for access_policies_list

        List access policys  # noqa: E501
        """
        pass

    def test_access_policies_partial_update(self):
        """Test case for access_policies_partial_update

        Update an access policy  # noqa: E501
        """
        pass

    def test_access_policies_read(self):
        """Test case for access_policies_read

        Inspect an access policy  # noqa: E501
        """
        pass

    def test_access_policies_reset(self):
        """Test case for access_policies_reset

        """
        pass

    def test_access_policies_update(self):
        """Test case for access_policies_update

        Update an access policy  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
