# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.repositories_gem_api import RepositoriesGemApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestRepositoriesGemApi(unittest.TestCase):
    """RepositoriesGemApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.repositories_gem_api.RepositoriesGemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repositories_gem_gem_add_role(self):
        """Test case for repositories_gem_gem_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_create(self):
        """Test case for repositories_gem_gem_create

        Create a gem repository  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_delete(self):
        """Test case for repositories_gem_gem_delete

        Delete a gem repository  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_list(self):
        """Test case for repositories_gem_gem_list

        List gem repositorys  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_list_roles(self):
        """Test case for repositories_gem_gem_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_modify(self):
        """Test case for repositories_gem_gem_modify

        Modify Repository Content  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_my_permissions(self):
        """Test case for repositories_gem_gem_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_partial_update(self):
        """Test case for repositories_gem_gem_partial_update

        Update a gem repository  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_read(self):
        """Test case for repositories_gem_gem_read

        Inspect a gem repository  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_remove_role(self):
        """Test case for repositories_gem_gem_remove_role

        Remove a role  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_set_label(self):
        """Test case for repositories_gem_gem_set_label

        Set a label  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_sync(self):
        """Test case for repositories_gem_gem_sync

        Sync from a remote  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_unset_label(self):
        """Test case for repositories_gem_gem_unset_label

        Unset a label  # noqa: E501
        """
        pass

    def test_repositories_gem_gem_update(self):
        """Test case for repositories_gem_gem_update

        Update a gem repository  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
