# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.task_schedules_api import TaskSchedulesApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestTaskSchedulesApi(unittest.TestCase):
    """TaskSchedulesApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.task_schedules_api.TaskSchedulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_schedules_add_role(self):
        """Test case for task_schedules_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_task_schedules_list(self):
        """Test case for task_schedules_list

        List task schedules  # noqa: E501
        """
        pass

    def test_task_schedules_list_roles(self):
        """Test case for task_schedules_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_task_schedules_my_permissions(self):
        """Test case for task_schedules_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_task_schedules_read(self):
        """Test case for task_schedules_read

        Inspect a task schedule  # noqa: E501
        """
        pass

    def test_task_schedules_remove_role(self):
        """Test case for task_schedules_remove_role

        Remove a role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
