# coding: utf-8

"""
    Pulp 3 API

    Fetch, Upload, Organize, and Distribute Software Packages  # noqa: E501

    The version of the OpenAPI document: v3
    Contact: pulp-list@redhat.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pulpcore.client.pulp_rpm
from pulpcore.client.pulp_rpm.api.publications_gem_api import PublicationsGemApi  # noqa: E501
from pulpcore.client.pulp_rpm.rest import ApiException


class TestPublicationsGemApi(unittest.TestCase):
    """PublicationsGemApi unit test stubs"""

    def setUp(self):
        self.api = pulpcore.client.pulp_rpm.api.publications_gem_api.PublicationsGemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_publications_gem_gem_add_role(self):
        """Test case for publications_gem_gem_add_role

        Add a role  # noqa: E501
        """
        pass

    def test_publications_gem_gem_create(self):
        """Test case for publications_gem_gem_create

        Create a gem publication  # noqa: E501
        """
        pass

    def test_publications_gem_gem_delete(self):
        """Test case for publications_gem_gem_delete

        Delete a gem publication  # noqa: E501
        """
        pass

    def test_publications_gem_gem_list(self):
        """Test case for publications_gem_gem_list

        List gem publications  # noqa: E501
        """
        pass

    def test_publications_gem_gem_list_roles(self):
        """Test case for publications_gem_gem_list_roles

        List roles  # noqa: E501
        """
        pass

    def test_publications_gem_gem_my_permissions(self):
        """Test case for publications_gem_gem_my_permissions

        List user permissions  # noqa: E501
        """
        pass

    def test_publications_gem_gem_read(self):
        """Test case for publications_gem_gem_read

        Inspect a gem publication  # noqa: E501
        """
        pass

    def test_publications_gem_gem_remove_role(self):
        """Test case for publications_gem_gem_remove_role

        Remove a role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
